### ISSUE TITLE
loss signature for generative models

### ISSUE THREAD

**Issue by bkmi** [mfederici/torch-mist#1]
https://github.com/mfederici/torch-mist/blob/7dace508b3097183227eb0c622a9a424d0ae295c/src/torch_mist/estimators/base.py#L18-L20

In the sbi extension, I regularize learning from a different proposal distribution by computing something like the normalizing constant. It requires access to `x_` alternatives.

see (29) and (40) in the overleaf.

Would you like to support this? If so, I would include an `x_` argument. (I think I can also get away with just overwriting the interface.)

**Comment by bkmi** [comment]
As I look into the interface more, I can tell this is going to be an issue generally.

The reason is because in sequential sbi we are generally going to be sampling from both `p_n(t) p(x|t)` and `p_0(x) := int p_0(t) p(x | t) dt` where `p_0(t)` is the prior.

**Comment by mfederici** [comment]
It seems that this requires quite some generalization to the framework to support Generalized KL.
I am not sure I would be able to support that in the early releases at least

**Comment by bkmi** [comment]
As I look more closely, I think this should be beyond the scope of the library. Certainly for now.
