### ISSUE TITLE
cache causes issues with pickle

### ISSUE THREAD

**Issue by bkmi** [mfederici/torch-mist#3]
The following code fails with an error on loading the pickle. It only fails once the loss has been called at least once, i.e. there is "something to pickle."

```python
import pickle

import torch
from torch_mist.estimators import JS
from torch_mist.critic import JointCritic
from torch import nn

# First we define a critic network that maps pairs of samples to a scalar
critic = JointCritic(
    joint_net=nn.Sequential(
        nn.Linear(10, 64),
        nn.ReLU(True),
        nn.Linear(64, 64),
        nn.ReLU(True),
        nn.Linear(64, 1),
    )
)

# We also specify the number of Monte Carlo samples to use for the estimation of the normalization constant
neg_samples = 16

# Then we pass it to the Jensen-Shannon estimator
mi_estimator = JS(
    critic=critic,
    neg_samples=neg_samples
)

mi_estimator.loss(x=torch.randn(10, 5), y=torch.randn(10, 5))

print(mi_estimator)

pickle.dumps(mi_estimator)
with open("js.pickle", "wb") as f:
    pickle.dump(mi_estimator, f)
print("Pickle dumps!")

with open("js.pickle", "rb") as f:
    loaded = pickle.load(f)
print("Pickle loads!")
```

Here is the error.

```bash
Exception has occurred: AttributeError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
'JS' object has no attribute '_reset_cache'
  File "/home/ben/mambaforge/envs/next2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
  File "/home/ben/sci/next/testing.py", line 38, in <module>
    loaded = pickle.load(f)
  File "/home/ben/mambaforge/envs/next2/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ben/mambaforge/envs/next2/lib/python3.8/runpy.py", line 194, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,
AttributeError: 'JS' object has no attribute '_reset_cache'
```

**Comment by bkmi** [comment]
I checked if all we needed was `functools.wraps`, [but it isn't enough](https://gael-varoquaux.info/programming/decoration-in-python-done-right-decorating-and-pickling.html). We should still use it on these [two functions](https://github.com/mfederici/torch-mist/blob/7dace508b3097183227eb0c622a9a424d0ae295c/src/torch_mist/utils/caching.py#L60-L76) though.

The issue is that the `@cache` decorator [modifies the attributes of the class](https://github.com/mfederici/torch-mist/blob/7dace508b3097183227eb0c622a9a424d0ae295c/src/torch_mist/utils/caching.py#L39-L42), making them invisible to `pickle` upon loading. (`pickle` only reads the static class, it doesn't evaluate decorators.)

I see the following ways to fix this:
- somehow use the `functools` caching, although it looks like it doesn't have the features we need.
- make being cacheable an inherited property. Then `pickle` will find the attributes when loading.
- custom design the pickling process (could be done using the `@cache` decorator) so the `__dict__` doesn't contain the offending attributes. Then, upon loading, those attributes are reintroduced. The details for that can be found [here](https://docs.python.org/3/library/pickle.html#pickling-class-instances). (I think we should avoid this option if possible.)

**Comment by bkmi** [comment]
Indeed I tested it by commenting out all the caching related decorators and it pickles just fine.

**Comment by mfederici** [comment]
Thanks for pointing this out.
The `_reset_cache` method was causing the issue.
Model Saving/Loading should work now

**Comment by mfederici** [comment]
Thanks for pointing this out.
The `_reset_cache` method was causing the issue.
Model Saving/Loading should work now
